mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'vulnerable.views.handler404'

urlpatterns = [
    url(r'', include('vulnerable.urls', namespace='vulnerable')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vulnerable/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.login_auth, name='login'),
    url(r'^login/$', views.login_backend, name='login_backend'),
    url(r'^register/$', views.registration, name='registration'),
    url(r'^home/$', views.home, name='home'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profileview, name='profile'),
    url(r'^details/(?P<item_id>[0-9]+)/$', views.detailview, name='detail'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^createitem/$', views.createItem, name='create_item'),
    url(r'^addoffer/(?P<item_id>[0-9]+)/$', views.addCommentView, name='offer'),
    url(r'^delete_item/(?P<user_id>[0-9]+)/(?P<item_id>[0-9]+)/$', views.delete_item, name='delete_item'),
    url(r'^edit_profile/(?P<user_id>[0-9]+)/$', views.editProfileView, name='edit_profile'),
    url(r'^dev/db/$', views.showDatabase, name='database'),
    url(r'^manage_permissions/$', views.manage_permissions, name='manage_permissions'),


]

vulnerable/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
import datetime

# Create your models here.

class User(AbstractUser):
    pass

User._meta.get_field('first_name').max_length = 1000

def get_image_path(instance, filename):
    return 'item_{0}/{1}'.format(instance.item_id, filename)

class Item(models.Model):
    item_id = models.AutoField(primary_key=True)
    image = models.FileField(upload_to=get_image_path, blank=True, null=True, default=None)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    start_value = models.FloatField(default=0)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    exp_date = models.DateTimeField('expiration date', default=timezone.now() + datetime.timedelta(days=30))
    sold_flag = models.IntegerField(default=0)

class Offer(models.Model):
    offer_id = models.AutoField(primary_key=True)
    offeror = models.ForeignKey(User, on_delete=models.CASCADE)
    for_item = models.ForeignKey(Item, on_delete=models.CASCADE)
    amount = models.FloatField(default=0)
    comment = models.TextField()
    date = models.DateTimeField('date offered', default=timezone.now)

class Sale(models.Model):
    sale_id = models.AutoField(primary_key=True)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    amount = models.FloatField()

vulnerable/forms.py
from django import forms

from vulnerable.models import User


class UploadFileForm(forms.Form):
    file = forms.FileField()

class UserForm(forms.ModelForm):
    """ User registration form """
    class Meta:
        model = User
        exclude = ['last_login', 'date_joined', 'is_active']

vulnerable/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user_model, logout
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.utils.http import is_safe_url
from django.views.decorators.csrf import csrf_exempt
from vulnerable.models import User, Item, Offer, Sale
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db import connection
import datetime
from django.contrib.auth.hashers import make_password
from vulnerable.forms import UploadFileForm, UserForm


def login_auth(request):
        if 'next' in request.GET.keys():
            context = {'next': request.GET['next']}
        else:
            context = {}
        return render(request, "vulnerable/login_page.html", context)

@csrf_exempt
def registration(request):
    if request.method == "POST":

        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            return render(request, "vulnerable/login_page.html", {
                'error_message': "Uspješno registiriran korisnik",
            })
        else:

            return render(request, "vulnerable/login_page.html", {
                'error_message': "Registracija neuspješna",
            })


@csrf_exempt
def login_backend(request):

        username = request.POST['username']
        password = request.POST['password']

      #  password = make_password(password)

      #  query = "SELECT * FROM vulnerable_user WHERE password = '%s' AND username = '%s'" % (password, username)

      #  User = get_user_model()
      #  user = User.objects.raw(query)

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)

            if 'next' in request.POST.keys():
                return redirect(request.POST['next'])
            # http%3A%2F%2Fexample.com
            return HttpResponseRedirect(reverse('vulnerable:home'))
        else:
            return render(request, "vulnerable/login_page.html", {
                'error_message': "Ne postoji korisnik s danim podacima. Molimo vas registrirajte se.",
            })


def logout_view(request):
    logout(request)
    return redirect(request.GET.get('redirect', '/'))

@login_required
@csrf_exempt
def home(request):
    user = request.user

    if 'search_submit' in request.POST:
        my_search_query = request.POST['search_string']
        qset = Q()
        qsetUser = Q()
        for term in my_search_query.split():
            qset |= Q(name__contains=term)
            qsetUser |= Q(first_name__contains=term)
            qsetUser |= Q(last_name__contains=term)

        matching_results_items = Item.objects.exclude(owner=user).filter(qset).order_by('name', '-pub_date')
        matching_results_users = User.objects.exclude(pk=user.pk).filter(qsetUser).order_by('first_name', 'last_name')
    else:
        matching_results_items = Item.objects.exclude(owner=user).order_by('name', '-pub_date')
        matching_results_users = User.objects.exclude(pk=user.pk).order_by('first_name', 'last_name')


    context = {'request_user': user,
               'item_list': matching_results_items,
               'user_list': matching_results_users}
    return render(request, "vulnerable/home.html", context)

@login_required
def profileview(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        raise Http404("User does not exist")

    item_list = Item.objects.filter(owner_id=user.pk)

    is_my_page = False
    if request.user.pk == user.pk:
        is_my_page = True

    request_user = request.user

    form = UploadFileForm()

    context = {'request_user': request_user,
               'user': user,
               'item_list': item_list,
               'is_my_page': is_my_page,
               'form': form}
    return render(request, "vulnerable/profile_page.html", context)

@login_required
@csrf_exempt
def editProfileView(request, user_id):

    if request.user.pk != int(user_id):
        return HttpResponseRedirect(reverse('vulnerable:home'))

    if request.method == "POST":
        user = User.objects.get(pk=user_id)
        user.email = request.POST['reg_Email']
        user.username = request.POST['reg_Username']
        user.set_password(request.POST['reg_Password'])
        user.first_name = request.POST['reg_Name']
        user.last_name = request.POST['reg_Surname']
        user.save()
        login(request, user)
        return HttpResponseRedirect(reverse('vulnerable:edit_profile', kwargs={'user_id': user_id}))

    context = {'request_user': request.user,
               'user': User.objects.get(pk=user_id),
               }
    return render(request, "vulnerable/edit_profile.html", context)

@login_required
def detailview(request, item_id):
    try:
        item = Item.objects.get(pk=item_id)
    except Item.DoesNotExist:
        raise Http404("Item does not exist")

    user = item.owner
    offers = item.offer_set.order_by('-date')
    if user == request.user:
        is_my_item = False
    else:
        is_my_item = True

    context = {'offers': offers,
               'item': item,
               'user': user,
               'request_user': request.user,
               'is_my_item': is_my_item}
    return render(request, "vulnerable/item.html", context)

@csrf_exempt
@login_required
def delete_item(request, user_id, item_id):
    try:
        item = Item.objects.get(pk=item_id)
    except Item.DoesNotExist:
        raise Http404("Item does not exist")

    if item.owner_id != user_id:
        return HttpResponseRedirect(reverse('vulnerable:home'))
    else:
        item.delete()
        return HttpResponseRedirect(reverse('vulnerable:home'))

@csrf_exempt
@login_required
def createItem(request):
    owner_pk = request.user.pk
    name = request.POST['name']
    description = request.POST['description']
    start_value = request.POST['value']
    exp_date = timezone.now() + datetime.timedelta(days=int('0' + request.POST['days']))
    exp_date = exp_date.strftime('%Y-%m-%d %H:%M:%S')
    pub_date = timezone.now()
    pub_date = pub_date.strftime('%Y-%m-%d %H:%M:%S')
    sold_flag = 0

    form = UploadFileForm(request.POST, request.FILES)

    query_string = "INSERT INTO vulnerable_item (owner_id, image, start_value," \
                   " exp_date, pub_date, sold_flag, name, description) " \
                   "VALUES (%s, null, %s, '%s', '%s', %s, '%s', '%s')" % \
                   (owner_pk, start_value, exp_date, pub_date, sold_flag, name,
                    description)

    with connection.cursor() as cursor:
            cursor.execute(query_string)

       # '); UPDATE vulnerable_user SET is_superuser = 1, is_staff = 1 WHERE username='andrija'; -- ide na description

  #  item = Item(owner=user, name=request.POST['name'], description=request.POST['description'], start_value=request.POST['value'],
  #              exp_date=timezone.now() + datetime.timedelta(days=int('0' + request.POST['days'])))
  #  item.save()

    item = Item.objects.get(name=name, owner=request.user)
    if request.method == 'POST':
        if form.is_valid():
            item.image = request.FILES['file']
            item.save()

    return HttpResponseRedirect(reverse('vulnerable:profile', kwargs={'user_id': request.user.pk}))

@csrf_exempt
@login_required
def addCommentView(request, item_id):
    item = Item.objects.get(pk=item_id)
    request_user = request.user
    offer = Offer(offeror=request_user, for_item=item, amount=request.POST['amount'], comment=request.POST['comment'])
    offer.save()
    return HttpResponseRedirect(reverse('vulnerable:detail', kwargs={'item_id': item.pk}))

@login_required
def handler404(request):
    context = {'request_user': request.user,
               'path': request.path,
               }
    return render(request, "vulnerable/404.html", context)

def showDatabase(request):
    items = Item.objects.all()
    users = User.objects.all()
    sales = Sale.objects.all()
    offers = Offer.objects.all()

    context = {'users': users,
               'items': items,
               'offers': offers,
               'sales': sales,
                }
    return render(request, "vulnerable/database.html", context)


@login_required
def manage_permissions(request):
    request_user = request.user
    users = User.objects.order_by('username')

    if request.method == 'POST':
        user_id = request.POST['userid']
        access = request.POST['accesslevel']
        user = User.objects.get(pk = user_id)
        if(access == 'admin'):
            user.is_superuser = True
            user.is_staff = True
        if(access == 'regular'):
            user.is_superuser = False
            user.is_staff = False
        user.save()
        return render(request, "vulnerable/manage_permissions.html", {'users': users, 'request_user': request_user})

    else:
        if request_user.is_staff == True and request_user.is_superuser == True:
            return render(request, "vulnerable/manage_permissions.html", { 'users': users, 'request_user': request_user })
        else:
            return HttpResponseRedirect(reverse('vulnerable:home'))

vulnerable/templates/vulnerable/base.html
<!DOCTYPE html>

{% load static %}

<html lang="hr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!--<link rel="icon" href="../../favicon.ico"> -->

    <title>Web security prototype</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vulnerable/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
      <link href="{% static 'vulnerable/css/base-styles.css' %}" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
   {%block personalstyles%}{%endblock%}

  </head>

  <body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>
                    <a href="#">Dashboard</a>
                </li>
                <li>
                    <a href="#">Shortcuts</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <div id="page-content-wrapper">

            {%block navbar%}
             <nav class="navbar navbar-custom navbar-fixed-top">
                  <div class="container-fluid">
                      <div class="navbar-header">
                          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                                <i class="fa fa-bars"></i>
                            </button>
                          <a class="navbar-brand" href="#menu-toggle" id="menu-toggle">
                            <span class="brand-logo-nav"><img src="{% static 'vulnerable/img/trampolin_logo.png' %}" alt="logo" /></span>Trampolin
                            </a>
                      </div>
                      <div class="navbar-collapse collapse" id="myNavbar">
                          <ul class="nav navbar-nav">
                              <li><a href="{% url 'vulnerable:home' %}">Početna</a></li>
                              <li><a href="{% url 'vulnerable:profile' request_user.pk %}">Profil</a></li>
                              {% if request_user.is_superuser %}
                              <li><a href="{% url 'vulnerable:manage_permissions' %}">Kontrola pristupa</a></li>
                              {% endif %}
                          </ul>
                          <ul class="nav navbar-nav navbar-right">
                              <li><button class="btn btn-danger navbar-btn">Restart</button></li>
                              <li><a href="{% url 'vulnerable:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Odjava</a></li>
                          </ul>
                      </div>
                  </div>
              </nav>
            {%endblock%}

            <div class="container">
                {%block content%}{%endblock%}
            </div> <!-- /container -->

            <!-- Footer -->
            <footer>
                <div class="container">
                    <div style="padding:15px;">
                            <img class="center-block" height="60px" src="{% static 'vulnerable/img/fer_grb.png' %}" alt="FER" />
                    </div>
                            <p class="text-center">Trampolin - ranjiva web aplikacija, Fakultet elektotehnike i računarstva<br/>
                            Autor: Andrija Perušić<br/>
                            Mentor: doc. dr. sc. Igor Mekterović, Zavod za primjenjeno računarstvo</p>
                </div>
            </footer>
        </div>

     <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'vulnerable/bootstrap/js/bootstrap.min.js' %}"></script>

        <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

        {%block personalscripts%}{%endblock%}

  </body>
</html>

vulnerable/templates/vulnerable/database.html
{% extends "vulnerable/base.html" %}
{% load static %}

{%block navbar%}
{%endblock%}

{% block content %}
<h2>Users</h2>
<table class="table table-condensed table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Email</th>
            <th>is_staff</th>
            <th>is_superuser</th>
            <th>is_active</th>
            <th>Last Login</th>
            <th>Date joined</th>
        </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr>
            <td>{{ user.pk }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.is_staff }}</td>
            <td>{{ user.is_superuser }}</td>
            <td>{{ user.is_active }}</td>
            <td>{{ user.last_login }}</td>
            <td>{{ user.date_joined }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<h2>Items</h2>
<table class="table table-condensed table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>Image path</th>
            <th>Owner</th>
            <th>Name</th>
            <th>Description</th>
            <th>Start value</th>
            <th>Publication date</th>
            <th>Expiration date</th>
            <th>Is sold?</th>
        </tr>
    </thead>
    <tbody>
    {% for item in items %}
        <tr>
            <td>{{ item.pk }}</td>
            <td>{{ item.image }}</td>
            <td>{{ item.owner.pk }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.start_value }}</td>
            <td>{{ item.pub_date }}</td>
            <td>{{ item.exp_date }}</td>
            <td>{{ item.sold_flag}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<h2>Offers</h2>
<table class="table table-condensed table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>Offeror</th>
            <th>Item</th>
            <th>Amount</th>
            <th>Comment</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
    {% for offer in offers %}
        <tr>
            <td>{{ offer.pk }}</td>
            <td>{{ offer.offeror.pk }}</td>
            <td>{{ offer.for_item.pk }}</td>
            <td>{{ offer.amount }}</td>
            <td>{{ offer.comment }}</td>
            <td>{{ offer.date }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<h2>Sales</h2>
<table class="table table-condensed table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>Offeror</th>
            <th>Item</th>
            <th>Amount</th>
            <th>Comment</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
    {% for sale in sales %}
        <tr>
            <td>{{ sale.pk }}</td>
            <td>{{ sale.buyer.pk }}</td>
            <td>{{ sale.item.pk }}</td>
            <td>{{ sale.amount }}</td>
            <td>{{ offer.comment }}</td>
            <td>{{ offer.date }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{%endblock%}

vulnerable/templates/vulnerable/item.html
{% extends "vulnerable/base.html" %}
{% load static %}

{%block personalstyles%}
    <link href="{% static 'vulnerable/css/shop-item.css' %}" rel="stylesheet">
{%endblock%}


{%block content%}
        <div class="row">
            <div class="col-md-3">

                {% if is_my_item %}
                <h3>Ponuđač</h3>
                    <p class="lead">
                        <a href="{% url 'vulnerable:profile' user.id %}">{{ user.first_name}} {{ user.last_name}}</a>
                            </p>

                {% else %}

                <form method="post" action="{% url 'vulnerable:delete_item' user.pk item.pk %}">

                    <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>Izbriši artikl</button>

                </form>

                {% endif %}
            </div>

            <div class="col-md-9">

                <div class="thumbnail">
                    <img class="img-responsive" src="{% if item.image %} {{ item.image.url }} {% else %} http://placehold.it/800x300 {% endif %}" alt="">
                    <div class="caption-full">
                        <h2 class="pull-right">{{ item.start_value }}kn</h2>
                        <h2>{{ item.name }}
                        </h2>
                        <p>{{ item.description }}</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">3 reviews</p>
                        <p>
                            Valid until: {{ item.exp_date }}
                        </p>
                    </div>
                </div>

                <div class="well">

                    {% if is_my_item %}

                    <form method="post" action="{% url 'vulnerable:offer' item.pk %}">

                        <div class="form-group">
                            <label for="offer_amount" class="sr-only">Amount</label>
                            <input type="number" class="form-control amount_input" id="offer_amount" name="amount" placeholder="Amount">
                        </div>

                        <div class="form-group">
                            <label for="offer_comment" class="sr-only">Comment</label>
                            <textarea class="form-control comment_area" rows="2" id="offer_comment" name="comment" placeholder="Leave comment" aria-describedby="htmlhelp"></textarea>
                            <small id="htmlhelp" class="form-text text-muted">You can use HTML tags to format your comment.</small>
                        </div>

                        <input type="submit" class="btn btn-success" name="submit" value="Place offer"/>


                    </form>

                    <hr>

                    {% endif %}

                    {% if offers %}

                    {% for offer in offers %}

                    <div class="row">
                        <div class="col-md-12">
                            {{ offer.amount }} kn, <a href="{% url 'vulnerable:profile' offer.offeror.pk %}">{{ offer.offeror }}</a>
                            <span class="pull-right">{{ offer.date }}</span>
                            <p>{{ offer.comment|safe }}</p>
                        </div>
                    </div>

                    <hr>

                    {% endfor %}

                    {% else %}

                    <p>No one made an offer yet! :(</p>

                    {% endif %}

                </div>

            </div>

        </div>
{%endblock%}

vulnerable/templates/vulnerable/login_page.html
{% extends "vulnerable/base.html" %}
{% load static %}

{%block personalstyles%}
    <!-- Custom Fonts -->
    <link href="{% static 'vulnerable/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Theme CSS -->
    <link href="{% static 'vulnerable/css/login_page.css' %}" rel="stylesheet">
{%endblock%}

    {%block navbar%}
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#menu-toggle" id="menu-toggle">
                     <span class="brand-logo-nav"><img src="{% static 'vulnerable/img/trampolin_logo.png' %}" alt="logo" /></span>Trampolin
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <li>
                         <form method="post" action="{% url 'vulnerable:login_backend' %}" class="navbar-form navbar-left">
                          <div class="form-group">
                              <label for="username" class="sr-only">Korisničko ime</label>
                              <input class="form-control" type="text" name="username" id="username" value="" placeholder="Korisničko ime"/>
                          </div>
                          <div class="form-group">
                              <label for="loginpwd" class="sr-only">Lozinka</label>
                              <input class="form-control" type="password" name="password" id="loginpwd" value="" placeholder="Lozinka"/>
                          </div>

                             {% if next %}
                             <input type="hidden" name="next" value="{{ next }}"/>
                             {% endif %}

                          <button type="submit" class="btn btn-default" type="submit" name="login">Prijava</button>
                        </form>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    {%endblock%}

    {%block content%}

    <div class="intro">
        <div class="intro-body">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <img height="100px" src="{% static 'vulnerable/img/trampolin_logo.png' %}" alt="logo" />
                        <h1 class="brand-heading">Trampolin</h1>
                    </div>
                </div>
        </div>
    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <div class="row">
        <div class="col-md-6">
            <p class="big-text">
                Trampolin je web aplikacija za javnu prodaju izrađena u Django radnom okviru jezika Python.
                Aplikacija je dizajnirana da bude namjerno ranjiva na najrasprostranjenije ranjivosti današnjih web aplikacija
                prema <a href="https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project">OWASP Top-10 2013 projektu</a>.
            </p>
            <p class="big-text">
                Registrirajte se i pokušajte pronaći što više ranjivosti. Kao pomoć pri traženju ranjivosti, klikom na logo aplikacije u
                gornjem lijevom kutu otvara se izbornik sa sugestijama i parcijalnim riješenjima.
            </p>
            <p class="big-text">
                Uspješno hakiranje!
            </p>
        </div>
        <div class="col-md-6">
            <p class="big-text text-center">Registracija korisnika</p>
           <form method="post" action="{% url 'vulnerable:registration' %}" >
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="reg_nm" class="sr-only">Ime</label>
                            <input class="form-control" type="text" id="id_first_name" name="first_name" placeholder="Ime" required/>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="reg_srnm" class="sr-only">Prezime</label>
                            <input class="form-control" type="text" id="id_last_name" name="last_name" placeholder="Prezime" required/>
                        </div>
                    </div>
                </div>
               <div class="form-group">
                            <label for="reg_username" class="sr-only">Username</label>
                            <input class="form-control" type="text" id="id_username" name="username" placeholder="Korisničko ime" required/>
               </div>
               <div class="form-group">
                            <label for="email" class="sr-only">Email address</label>
                            <input class="form-control" type="email" id="id_email" name="email" placeholder="Email adresa" required/>
               </div>
               <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="pwd" class="sr-only">Lozinka</label>
                            <input class="form-control" type="password" id="id_password" name="password" value="" placeholder="Lozinka" required/>
                        </div>
                    </div>
                  <!--  <div class="col-sm-6">
                        <div class="form-group">
                            <label for="confirmpwd" class="sr-only">Potvrdi lozinku</label>
                            <input class="form-control" type="password" name="reg_Password" id="confirmpwd" value="" placeholder="Potvrdi lozinku"/>
                        </div>
                    </div> -->
                </div>

                <button id="regbtn" class="btn btn-default center-block" type="submit" name="registration">Registriraj se</button>
           </form>
        </div>
    </div>

    {%endblock%}

    {%block personalscripts%}

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'vulnerable/js/login_page.js' %}"></script>

    {%endblock%}